server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.30.110:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.30.110
    virtual-host: /gmall
    username: gmall
    password: gmall