server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.30.110
  rabbitmq:
    host: 192.168.30.110
    port: 5672
    virtual-host: /gmall
    username: gmall
    password: gmall
gmall:
  jwt:
    pubKeyPath: D:\JetBrains\IdeaProjects\Microservices\gmall_project\rsa\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
alipay:
  app_id: 2016102300747414
  merchant_private_key:
  alipay_public_key:
  notify_url: http://1gleaaw0tb.52http.tech/api/order/pay/success
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do