server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.30.110
  rabbitmq:
    host: 192.168.30.110
    port: 5672
    virtual-host: /gmall
    username: gmall
    password: gmall
gmall:
  jwt:
    pubKeyPath: D:\JetBrains\IdeaProjects\Microservices\gmall_project\rsa\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key