server:
  port: 8093
spring:
  application:
    name: shortMessage-service
  rabbitmq:
    host: 192.168.30.110
    port: 5672
    virtual-host: /gmall
    username: gmall
    password: gmall
gmall:
  sms:
    accessKeyId:  # accessKeyId
    accessKeySecret:  # AccessKeySecret
    signName: # 签名名称
    verifyCodeTemplate:  # 模板名称